export const subjects = [
  'Cálculo Diferencial',
  'Cálculo Integral',
  'Cálculo Multivariable',
  'Álgebra Lineal',
  'Ecuaciones Diferenciales',
  'Física Mecánica',
  'Física de Campos',
  'Programación Básica',
  'Programación Orientada a Objetos',
  'Estructuras de Datos',
  'Algoritmos',
  'Bases de Datos',
  'Estadística Descriptiva',
  'Probabilidad y Estadística',
  'Economía General',
  'Contabilidad Financiera',
  'Química General',
  'Química Orgánica',
  'Biología Celular',
  'Inglés',
];
